language: minimal
env: GO111MODULE=on
git:
  depth: 1
install:
  - eval "$(gimme)"
stages:
  - name: 'Lint markdown files'
  - 'Lint'
  - 'Unit test'
  - 'Benchmark test'  
  - 'Integration tests'
  - 'Source clear'
jobs:
  include:
    - stage: 'Lint markdown files'
      os: linux
      language: generic
      install: gem install awesome_bot
      script:
        - find . -type f -name '*.md' -exec awesome_bot {} \;
      notifications:
        email: false

    - stage: 'Lint markdown files'
      os: linux
      language: generic
      before_install: skip
      install:
        - npm i -g markdown-spellcheck
      before_script:
        - wget --quiet https://raw.githubusercontent.com/optimizely/mdspell-config/master/.spelling
      script:
        - mdspell -a -n -r --en-us '**/*.md'
      after_success: skip

    - stage: 'Lint'
      env: GIMME_GO_VERSION=1.13.x GIMME_OS=linux GIMME_ARCH=amd64
      script:
        - make install lint

    - &test
      stage: 'Unit test'
      env: GIMME_GO_VERSION=master GIMME_OS=linux GIMME_ARCH=amd64
      script:
        - make cover

    - <<: *test
      stage: 'Unit test'
      env: GIMME_GO_VERSION=1.10.x
      before_script:
        - go get github.com/mattn/goveralls
      after_success:
        - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

    - <<: *test
      stage: 'Unit test'
      env: GIMME_GO_VERSION=1.14.x
      before_script:
        - go get github.com/mattn/goveralls
      after_success:
        - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

    - stage: 'Benchmark test'
      env: GIMME_GO_VERSION=master GIMME_OS=linux GIMME_ARCH=amd64
      script:
        - make benchmark

    - stage: 'Integration tests'
      env: SDK=go SDK_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH
      cache: false
      language: minimal
      install: skip
      before_script:
        - mkdir $HOME/travisci-tools && pushd $HOME/travisci-tools && git init && git pull https://$CI_USER_TOKEN@github.com/optimizely/travisci-tools.git && popd
      script:
        - $HOME/travisci-tools/trigger-script-with-status-update.sh
      after_success: travis_terminate 0
    
    - stage: 'Source clear'
      env: GIMME_GO_VERSION=master GIMME_OS=linux GIMME_ARCH=amd64
      language: go
      addons:
        srcclr: true
      script: go get -v -d ./...
